### ISSUE TITLE
Icon request: GOV.UK

### ISSUE THREAD

**Issue by jahed** [krisu5/aegis-icons#375]
- URL of the site or app **(required):** https://www.gov.uk/
- Logo resources for the icon **(optional, but recommended):** https://en.wikipedia.org/wiki/File:Gov.uk_logo.svg

**Comment by jahed** [comment]
I noticed HMRC was added in #136, but this isn't the same as GOV.UK (the broader login that includes more than just HMRC). GOV.UK has a different crown and also uses a black background with white lineart.

**Comment by krisu5** [comment]
> but this isn't the same as GOV.UK (the broader login that includes more than just HMRC). 

Okay, I will replace it with this icon then, if that's the case.

**Comment by jahed** [comment]
Replacing it makes sense. Would that break anything for existing users of the icon?

I think HMRC used its own login system in the past, but seems to have migrated fully to GOV.UK's login system. 

The "sign in" link leads to GOV.UK's login: https://www.gov.uk/log-in-register-hmrc-online-services
And HMRC services are listed under: https://en.wikipedia.org/wiki/GOV.UK_Verify

**Comment by krisu5** [comment]
> Would that break anything for existing users of the icon?

It doesn't, the attached SVG of 2FA entry is stored to database and also included in the export JSON. Icons will also stay in the entries if you remove the icon pack from the app.

**Comment by krisu5** [comment]
I decided not to remove HMRC icon but instead move it to "Outdated" category / directory.

Didn't use the black color, because in the [design system doc](https://design-system.service.gov.uk/styles/colour/) says that this blue color is brand color.

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/GOV.UK.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
