### ISSUE TITLE
Icon request: Toyohashi University of Technology

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#382]
- URL of the site or app **(required):** https://imc.tut.ac.jp/
- Logo resources for the icon **(optional, but recommended):** [PNG](https://www.tut.ac.jp/sotsuren/img/icon/logo-mark.png), [JPG](http://fluid.mech.kogakuin.ac.jp/~iida/images/log02.jpg)

**Comment by krisu5** [comment]
> Logo resources for the icon **(optional, but recommended):** [PNG](https://www.tut.ac.jp/sotsuren/img/icon/logo-mark.png), [JPG](http://fluid.mech.kogakuin.ac.jp/~iida/images/log02.jpg)

Are you sure that this is the current logo? Logo in the website is [totally different](https://www.tut.ac.jp/english/imgs/base/logo.gif) and Google's image search says the same.

I can make the icon based of current website's logo, because that's simple enough to do by hand. But with logo images that you provided, I can't do it with using image tracing and takes too much time to do by hand (unless there's much higher quality image).

*P.S. Next time, please read carefully the bottom of the issue template too.*

**Comment by ghost** [comment]
This is the current logo.
https://www.tut.ac.jp/kikin/
https://www.tut.ac.jp/sotsuren/
https://www.tut.ac.jp/about/index.html

**Comment by ghost** [comment]
Toyohashi University of Technology has two logos.
The first is a red and black "T". This is always used colored in red and black. This is why it does not go well with the Aegis-icon. 

The other logo I suggested can also be used in black and white, and given the design of the Aegis-icons, it is the only one that can be used.

**Comment by ghost** [comment]
https://commons.wikimedia.org/wiki/File:Toyohashi_university_of_science_and_technology_emblem.JPG

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Toyohashi%20University%20of%20Technology.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
