### ISSUE TITLE
Icon request: Alpha Host

### ISSUE THREAD

**Issue by EinfachRuwen** [krisu5/aegis-icons#449]
- URL of the site or app **(required):** https://panel.alpha-host.de/
- Logo resources for the icon **(optional):** https://cdn.discordapp.com/icons/801904571021656074/b8c9fff8fb005061ff5036b35eaec378.webp?size=2048

**Comment by krisu5** [comment]
URL is not acceptable, because it's login screen with no links to homepage. And just going to `alpha-host.de` brings server not found error (if it works on your end, please tell, this might be region block). Googling also doesn't bring clear results.

Discord channel icon images count to "no profile pictures" rule, specially since these are small images. 

If there's no better URL to the website, I will reject this in 1 week.

**Comment by EinfachRuwen** [comment]
Problem is: There isn't a Website yet. 
You can visit the Discord-Server here: https://discord.gg/HdHzzcGTQP

Alpha-Host is a free Hoster over Discord.  So I can send a Message to someone, if you want, if someone can send me the svg or png for the Logo

**Comment by krisu5** [comment]
Then this is similar situation then #411.

Sorry, I'm rejecting this. Request again when there's actual website.

**Comment by EinfachRuwen** [comment]
Okay.
