### ISSUE TITLE
Icon request: Libero

### ISSUE THREAD

**Issue by Big-Iron-Cheems** [krisu5/aegis-icons#513]
### URL of the site or app

~~https://play.google.com/store/apps/details?id=it.italiaonline.mail~~

https://www.libero.it/

### Anything else?

[This](https://lh3.googleusercontent.com/XbQB59-_0_l_jWxmt5lKi3LJDDmTRXlMZZYDhYv2XNV97B4K0lLOXfRFni-AIXu3SxY) is the logo on the app and mail service web page (512x512 PNG).
It's green and white, so making it monochrome should be possible.

They have an [alternative logo](https://asset.brandfetch.io/idUePihWv8/id8a677AWe.png), used in the favicon of the login page (128x128 PNG).

The website supports Aegis 2FA.
Couldn't find an SVG version on the website or through the [suggested websites](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#logos).

PS: Really appreciate the effort you put in this project, thank you for your service 👍

**Comment by krisu5** [comment]
Changed to just "Libero", because Libero Mail is sub-brand of Libero and account is called "Libero account" on registration page (like for example: Gmail is sub-brand of Google and calls accounts "Google accounts" for Gmail etc.)

Logo SVG: https://i.plug.it/mail/login/2020/libero/img/logo.svg (from Libero registration page).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Libero.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
