### ISSUE TITLE
Icon submission: CybelAngel

### ISSUE THREAD

**Issue by Ailothaen** [krisu5/aegis-icons#523]
### Icon type

Logo based

### URL of the site or app

https://cybelangel.com/

### Logo / icon info

Embedded SVG logo present in the header: https://cybelangel.com/

### Background color info

Background color is from the logo.

### Upload icon(s)

[Cybelangel](https://user-images.githubusercontent.com/11133116/155898491-993b074e-aeb4-4356-9b86-22a04d75d6c8.svg)

### Confirmation

- [X] I have read and **carefully** followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md)

**Comment by krisu5** [comment]
You forgot to [compress the SVG](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#svg-compression--cleanup).

I don't recommend uploading SVGs without zipping currently, [because it's currently buggy](https://github.com/github/feedback/discussions/11053).

Also, next time, be bit more clear about BG color. The header logo was white and footer one was colored.

**Comment by Ailothaen** [comment]
Here is a zipped version: [Cybelangel.zip](https://github.com/aegis-icons/aegis-icons/files/8149409/Cybelangel.zip)

However, I already had compressed the SVG before. I ran the `svgo` command on the file again but it did not change anything to the file.

**Comment by krisu5** [comment]
Ahh, okay, my bad.

There's just pointless stroke related junk code in the SVG, that SVGO doesn't touch because it doesn't know if it's important or not.

I remove the junk myself this time, but next time [check that SVG is cleaned up further by manual editing](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#svg-compression--cleanup) (the example SVG code).

**Comment by krisu5** [comment]
Added to the repo.
