### ISSUE TITLE
Icon submission: LocalMonero

### ISSUE THREAD

**Issue by nice42q** [krisu5/aegis-icons#539]
### Icon type

Logo based

### URL of the site or app

https://localmonero.co/

### Logo / icon info

https://svgur.com/s/65G

### Upload icon(s)

https://svgur.com/s/65G

### Confirmation

- [X] I have read and **carefully** followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md)

**Comment by krisu5** [comment]
This submission is rejected for not giving enough information of the submission (logo / icon info isn't sufficient, no background color info, "upload icon(s)" section URL is same as "logo / icon info") and also, this has been requested long time ago (#91) and reason why I didn't make icon for this service is because logo is exactly the same as Monero currency symbol. I still think it's kinda reduntant. Replacement is "Monero" icon on the generic section.
