### ISSUE TITLE
Icon submission: Ripio

### ISSUE THREAD

**Issue by sebastianserrani** [krisu5/aegis-icons#565]
### Icon type

Logo based

### URL of the site or app

https://www.ripio.com

### Logo / icon info

Image traced of https://ripio-cms-us.s3.amazonaws.com/filer_public/55/8e/558e23db-b6ad-43ce-9bcd-3a67e07b0244/logo_ripio.svg

### Background color info

Background color is accent color frow web page.

### Upload icon(s)

[Ripio.zip](https://github.com/aegis-icons/aegis-icons/files/8400631/Ripio.zip)

### Confirmation

- [X] I have read and **carefully** followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md)

**Comment by krisu5** [comment]
Use full logo, don't make it based of favicon.

BG is fine in this case, since logo's color varies a lot and there's no brand guidelines. Usually though background color should be taken from logo.

You should also tell where **exactly** you got the color from the website, but it let it pass **for this time only**, because I found the color you used.

_And just a small note: image tracing means making vector out of raster image (eg. JPG to SVG), so sentence "image traced of" with link to SVG doesn't make sense._

**Comment by sebastianserrani** [comment]
Sorry, again! posted in a hurry... About the logo, actually, I only took the "diamond" part (the dot in the i's) and put it in the circle with the adequate proportions, as I didn't found any kind of vector of their logo.
These are the only two I've got: https://theme.zdassets.com/theme_assets/1330097/fc15181ade7b651b956457cb7f9e460c7a91a05f.png and https://ripio-cms-us.s3.amazonaws.com/filer_public/3d/8f/3d8f5b2a-3fb7-44a9-b752-9fd1817e5c25/icon_rpc.png (the logo pointing to their crypto coin).
I've changed the background color to (#7908ff) which is the BG color on the first image.
Hope this helps 👋

[Ripio.zip](https://github.com/aegis-icons/aegis-icons/files/8411917/Ripio.zip)

**Comment by krisu5** [comment]
I don't see that "diamond" as logo, because website header SVG and social media profile pictures are all using the text-based logo.

Just make icon based of this logo with no changes to the shape: https://ripio-cms-us.s3.amazonaws.com/filer_public/55/8e/558e23db-b6ad-43ce-9bcd-3a67e07b0244/logo_ripio.svg

**Comment by sebastianserrani** [comment]
The "diamond" polygon used to be their logo... anyways... changed as requested.
[Ripio.zip](https://github.com/aegis-icons/aegis-icons/files/8412378/Ripio.zip)

**Comment by krisu5** [comment]
Added to the repo!
