### ISSUE TITLE
Icon request: popads

### ISSUE THREAD

**Issue by jakariyaa** [krisu5/aegis-icons#598]
### URL for the brand / site / app

https://www.popads.net/

### Logo resources for the icon

https://static.popads.net/img/logo.png

**Comment by krisu5** [comment]
There's no way that me or anyone else is willing to make icon for popunder ad network, because I consider popunders as malvertising / dark pattern.

EDIT: updated [icon acceptability criteria](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#icon-acceptability-criteria) related to ad networks.
