### ISSUE TITLE
Icon request: Kyoto University

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#608]
### URL for the brand / site / app

https://www.kyoto-u.ac.jp/en

### Logo resources for the icon

https://www.career.gakusei.kyoto-u.ac.jp/wp-content/themes/gssc_ku-child/images/logo_kyoto-u.svg

**Comment by krisu5** [comment]
I had to remove middle bottom parts of the logo because of density.

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Kyoto%20University.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
