### ISSUE TITLE
Icon request: YouTube

### ISSUE THREAD

**Issue by vairag22** [krisu5/aegis-icons#645]
### URL for the brand / site / app

https://youtube.com

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Rejected. YouTube is sub-brand of Google and YouTube uses Google accounts.

Use **Google** icon.

**Comment by vairag22** [comment]
> YouTube is sub-brand of Google

No, YT is a subsidiary of Alphabet Inc., like Google, Android and FitBit. That's why:
 
- YouTube is just YouTube, not Google YouTube.
- YT doesn't use Google's standard quad-tone colors for its icon.
- YT has its own CEO and other employees.

> YouTube uses Google accounts

Well, that's what happens when large corps acquire smaller companies. Meta mandated FB account for operating Oculus Quest 2 (changed after backlash), Amazon account is required to get Twitch Prime benefits, Microsoft account for Skype, etc.

Many people have a separate Google account for their YT channels, or just for privacy and security reasons. That's why I requested the icon, so users can easily distinguish between their regular Google accounts and YT accounts. Please consider this as well.

**Comment by krisu5** [comment]
> No, YT is a subsidiary of Alphabet Inc., like Google, Android and FitBit.

*Technically correct*, doesn't change a thing and it's beside the point I was making. It's still part of **Google** because of account system.

People don't think about Alphabet when they think about YouTube, they think of Google.

> Many people have a separate Google account for their YT channels, or just for privacy and security reasons.

That's edge case, most of the people (I argue that even the users of Aegis) don't have multiple Google accounts for this purpose. We don't make icons for these kinds of edge cases.

And nothing stops you or anyone just:
- reusing the Google icon or
- [changing the BG color of the icon](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#how-can-i-make-icon-with-different-background-color)

I stand by my point, as I have from the start of the project.
