### ISSUE TITLE
Icon request: Adobe

### ISSUE THREAD

**Issue by theflazy** [krisu5/aegis-icons#651]
### URL for the brand / site / app

https://www.adobe.com/

### Logo resources for the icon

https://www.adobe.com/content/dam/cc/icons/Adobe_Corporate_Horizontal_Red_HEX.svg

### Anything else?

2FA exists during signing in, between email and password entries.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Similar issue: #534

We had the icon on the pack, but [Adobe removed official 3rd party 2FA support](https://helpx.adobe.com/manage-account/using/secure-your-adobe-account.html) (only supporting legacy users) and there's no workarounds for new users ([part of "icon acceptability criteria"](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#not-approved)).

We moved the icon to ["removed icons section"](https://github.com/aegis-icons/misc/tree/main/removed_icons#readme) because of these reasons: \
https://github.com/aegis-icons/misc/blob/main/removed_icons/Adobe.svg
