### ISSUE TITLE
Update icon: Google

### ISSUE THREAD

**Issue by alphanerdgen** [krisu5/aegis-icons#662]
### URL for the brand / site / app

https://google.com

### Reason for update

Updated brand color

### Logo resources for the icon

https://uxwing.com/google-color-icon/

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
No need for update, BG color is from [Google's G logo symbol's](https://madeby.google.com/static/images/google_g_logo.svg) blue section (`#4285F4`). Blue is the Google's most used color, so that's why we choose that.

Similar to https://github.com/aegis-icons/aegis-icons/issues/140#issuecomment-735439804, we also will not make BG variations for other colors ([as also stated in the FAQ](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#can-you-make-variation-for-x-icon)). If you really want to, [make yourself](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#how-can-i-make-icon-with-different-background-color).
