### ISSUE TITLE
Icon request: Mint Mobile

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#691]
### URL for the brand / site / app

https://mintmobile.com

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by justsomemate** [comment]
I've been unable to find a good SVG resource for their fox mascot.
The closest I've seen is this (https://www.mintmobile.com/wp-content/themes/mintmobile/v3/assets/images/magnifyingfox.svg), which has a little different appearance than seen elsewhere (the down-turned ear doesn't fold to the center of the ear; the glasses are a little smaller) and has composing elements that make it more difficult to collapse to a single path. I made an effort to modify it to suit the requirements but ended up postponing the work when I got down to making the single path.
They do have a source SVG for the word mark (https://cdn.mintmobile.com/wp-content/themes/mintmobile/v3/assets/images/MM_Logo_Horizontal.svg) that I fit into the template until I or someone else works up the fox icon.

[Mint Mobile.zip](https://github.com/aegis-icons/aegis-icons/files/9691320/Mint.Mobile.zip)

For reference, their Android app uses this as the app icon but only has a PNG source:
![image](https://user-images.githubusercontent.com/80608392/193431061-cc00b3de-3f5d-4350-82c5-3ffafcff4b8e.png)

**Comment by krisu5** [comment]
@justsomemate If you're filling the request, you must create submission issue or PR: #560. Then we can talk about adding this to the pack.

*About the mascots:* unless it's clearly corporated part of the logo, use the actual logo instead.

In this case, actual logo is better option, since the fox isn't logomark.

The logo also can be changed to multi-line, since the brand allows it based of social media: https://twitter.com/Mintmobile/photo

Just try to make it similar as possible using that image as reference.

**Comment by krisu5** [comment]
Filled by #701:

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Mint%20Mobile.svg
