### ISSUE TITLE
Icon request: Polytoria

### ISSUE THREAD

**Issue by d4f5409d** [krisu5/aegis-icons#800]
### URL for the brand / site / app

https://polytoria.com

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Couldn't find anything related to 2FA inside of this service / site.

If you want this open again, either comment with:
- Link to documentation page related to 2FA **(prefered option)**
- Screenshot proof of the TOTP / Google Authenticator 2FA settings page _(censor sensitive info if needed)_.

**Comment by d4f5409d** [comment]
Man you really need proof

I can't take screenshots in Aegis
You need a Polytoria account to set up 2fa in the settings
You'll see it it's a qr code
Ty

**Comment by krisu5** [comment]
Yes, we are enforcing this policy. It's number one guideline, because we have got too many requests that don't have 2FA at all and people use our icon set as guide if service indeed has 2FA.

Please take a screenshot from Polytoria's 2FA settings page / 2FA prompt on login etc. (**no screenshots from Aegis app**) if you want this open again, censor sensitive info if needed *or* find documentation page / other mention related to 2FA from their site. See #797's "Proof of the Aegis-compatible 2FA" as example.
