### ISSUE TITLE
Update icon: Wellfound (f.k.a. AngelList Talent)

### ISSUE THREAD

**Issue by simonhollingshead** [krisu5/aegis-icons#809]
### URL for the brand / site / app

https://angel.co/

### Reason for update

New logo

### Logo resources for the icon

https://angel.co/logo

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
I kinda knew this already, but there's also https://www.angellist.com/ that still has its branding and name.

So I'm not sure if this is actually update or new icon. Wellfound likely is more popular though.

EDIT: I think I make this as update, since in 2FA Directory, the AngelList entry relates to rebranded Wellfound.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Wellfound.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
