### ISSUE TITLE
Icon request: WHM (Web Host Manager)

### ISSUE THREAD

**Issue by simonhollingshead** [krisu5/aegis-icons#812]
### URL for the brand / site / app

https://cpanel.net/

### Logo resources for the icon

https://cpanel.net/company/cpanel-brand-guide/ -> https://cpanel.net/wp-content/themes/cPbase/assets/downloads/logos/WHM_logos.zip (contains EPS)

### Proof of the Aegis-compatible 2FA

https://docs.cpanel.net/whm/security-center/two-factor-authentication-for-whm/

### Anything else?

You already have a logo for cPanel.  However, WHM is a second part of the platform (Web Host Manager) which may be separately deployed.  In some hosting situations where you get an account that can delegate to other accounts, you have both a WHM login (the reseller pages that manage all hosting accounts) and a cPanel login (the end user pages which administer that singular hosting account).

I should also note that while you do have a logo for WHMCS, WHMCS is not the same thing as WHM.  (https://support.cpanel.net/hc/en-us/articles/1500004803362-What-is-the-difference-between-WHM-and-WHMCS-)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Usually I reject requests that are based of sub-brand (like this case, cPanel is the master brand), but since you had a good reason for it and I confirmed that cPanel and WHM systems indeed have seperate accounts, I accepted this one.

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/WHM.svg

:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
