### ISSUE TITLE
Icon request: Saber

### ISSUE THREAD

**Issue by m0byn** [krisu5/aegis-icons#867]
### URL for the brand / site / app

https://github.com/adil192/saber

### Proof of the Aegis-compatible 2FA

![Screenshot](https://user-images.githubusercontent.com/33026003/225851984-ac3cafb2-2dfb-4c42-b614-db1a5e6066f3.png)

### Anything else?

2FA is needed to login to the website. There you can manage devices, keys, and others. For the Saber app itself, no 2FA is needed. However, in order to login to the Saber app, one needs to create passwords on the website!

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Unfortunately we have to reject this based of icon acceptability criteria ([Case-by-case basis ➜ Self-hosted or similar software ➜ "Suggested to have ≥ 500 GitHub / Gitlab stars or other non-maintainer activity to back it up."](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#case-by-case-basis)).

As alternative option, you could use **Nextcloud** icon (since it's using that) or generic **Notes** icon.
