### ISSUE TITLE
Icon request: Pexpay

### ISSUE THREAD

**Issue by imelwebs** [krisu5/aegis-icons#918]
### URL for the brand / site / app

https://www.pexpay.com

### Logo resources for the icon

https://theme.zdassets.com/theme_assets/11553545/166686281f302523ab92f24c3016485895e4426f.svg

### Proof of the Aegis-compatible 2FA

https://support.pexpay.com/hc/en-us/articles/9167249004185-How-to-Enable-Google-Authentication-2FA-and-Disable-SMS-Authentication

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Rejected because of "[icon acceptability criteria](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#icon-acceptability-criteria)":

> - Scams or other shady apps / sites.

Possible scam:

https://antiscam-reviews.com/pexpay
https://www.scamadviser.com/check-website/pexpay.com

**Comment by imelwebs** [comment]
I checked the links you shared about Pexpay's scam rating, and I feel that the reviews are not really clear and are based on only a few opinions. If you look at Scamadviser's page for Binance, you'll see that there are people complaining about their funds getting locked and calling it a scam too.

What's important to know is that Pexpay is actually unofficially connected to Binance. If someone from Russia uses Binance's P2P page, they're advised to switch to Pexpay as a "partner." This setup is so that Pexpay can get funds from Russian sanctioned banks' accounts without being directly linked to Binance.

With this connection between Pexpay and Binance in mind, I think it's worth taking another look at why Pexpay's icon was rejected. I'm asking if you could please reconsider the decision and let Pexpay's icon be a part of aegis-icons.


Best wishes,

Henry

**Comment by krisu5** [comment]
I reconsider it, but based of WikiFX / WikiBit (sites that rate and give info if broker is legit or not), says that it doesn't have license or valid regulation: https://www.wikibit.com/en/dr/1325111885020.html

And lack of info anywhere makes it even suspisious (and I think they have bought fake Twitter followers...)

**This is final decision**, even if you still think it's legit.

---

We are now more harsh to (crypto) trading sites / exchanges, because:

1. So many of them are scams, work illegally or other shady stuff.
2. There's too many requests / icons for them and we want to limit them.

We continue to check our current crypto / other trading & exchange icons from possible scams and other shady stuff and remove them if necessary.

---

There's plenty of generic icons that fill your need (bitcoin, finance, money etc.)
