### ISSUE TITLE
Icon request: Notion

### ISSUE THREAD

**Issue by nikhilbadyal** [krisu5/aegis-icons#930]
### URL for the brand / site / app

https://www.notion.so/

### Logo resources for the icon

https://www.notion.so/Media-Kit-205535b1d9c4440497a3d7a2ac096286

### Proof of the Aegis-compatible 2FA

[Notion 2FA Doc](https://www.notion.so/help/two-step-verification)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Duplicated issue: #909.

Please use search on our [website](https://aegis-icons.github.io/) and [issues section](https://github.com/aegis-icons/aegis-icons/issues?q=is%3Aissue) before submitting any issues.

**Comment by nikhilbadyal** [comment]
I checked it [do](https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Notion.svg
) exist. But unable to search. Am I missing something or any idea.


![image](https://github.com/aegis-icons/aegis-icons/assets/59223300/30869693-c27e-4f92-8c5c-1ca64453861f)

**Comment by krisu5** [comment]
It's not on the icon pack, because it was requested **after** the latest pack release.

That's why you should **always** check our [website](https://aegis-icons.github.io/) and [issues section](https://github.com/aegis-icons/aegis-icons/issues?q=is%3Aissue) first if there's any requests made.

Also from the issue guidelines:

> - Icon packs are updated monthly, not every time a new icon is created ([see the pack releases](https://github.com/aegis-icons/aegis-icons/releases)). Icons created after the latest pack update are downloadable on [the website](https://aegis-icons.github.io/).

You'll need to either download Notion icon SVG from our website and [add it manually to the entry](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually) or wait next icon pack update.

**Comment by nikhilbadyal** [comment]
Thanks for the explanation.
